update android-build.yml

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -20,6 +20,46 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+      - name: ensure lite files also updated
+        run: |
+          git fetch origin ${{ github.event.pull_request.base.sha }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
+          git fetch origin ${{ github.event.pull_request.head.sha }}:refs/remotes/origin/${{ github.event.pull_request.head.ref }}
+          echo "GITHUB_BASE_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
+          echo "GITHUB_HEAD_REF=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
+
+          files=("app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt"
+                 "app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite"
+                 "app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt"
+                 "app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite"
+                 "app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt"
+                 "app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite")
+
+          check_file_pair() {
+              local file1=$1
+              local file2=$2
+
+              # Check if either file has been modified in the commit range
+              if git diff --name-only "$GITHUB_BASE_REF".."$GITHUB_HEAD_REF" | grep -E "^($file1|$file2)$" > /dev/null; then
+                  # Check if both files are modified in the commit range
+                  git diff --name-only "$GITHUB_BASE_REF".."$GITHUB_HEAD_REF" | grep -E "^($file1)$" > /dev/null
+                  file1_changed=$?
+                  git diff --name-only "$GITHUB_BASE_REF".."$GITHUB_HEAD_REF" | grep -E "^($file2)$" > /dev/null
+                  file2_changed=$?
+
+                  if [ $file1_changed -ne 0 ] || [ $file2_changed -ne 0 ]; then
+                      echo "Error: Both $file1 and $file2 must be changed together."
+                      exit 1
+                  fi
+              fi
+          }
+
+          # Check each pair of files
+          for ((i=0; i<${#files[@]}; i+=2)); do
+              check_file_pair "${files[i]}" "${files[i+1]}"
+          done
+
+          echo "All file pairs have consistent changes."
+
       - name: diff the code to get lite
         run: |
           if [[ "${{ matrix.build }}" == "lite" ]]; then
