Update android-release.yml

diff --git a/.github/workflows/android-release.yml b/.github/workflows/android-release.yml
--- a/.github/workflows/android-release.yml
+++ b/.github/workflows/android-release.yml
@@ -54,25 +54,30 @@ jobs:
           distribution: 'zulu'
           java-version: '17'
 
-      - name: cache NDK
-        id: cache-ndk
-        uses: actions/cache@v4
-        with:
-          path: ${{ env.ANDROID_SDK_ROOT }}/ndk/${{ env.ANDROID_NDK_VERSION }}
-          key: ${{ runner.os }}-ndk-${{ env.ANDROID_NDK_VERSION }}
-          restore-keys: |
-            ${{ runner.os }}-ndk-
+#      - name: cache NDK
+#        id: cache-ndk
+#        uses: actions/cache@v4
+#        with:
+#          path: ${{ env.ANDROID_SDK_ROOT }}/ndk/${{ env.ANDROID_NDK_VERSION }}
+#          key: ${{ runner.os }}-ndk-${{ env.ANDROID_NDK_VERSION }}
+#          restore-keys: |
+#            ${{ runner.os }}-ndk-
 
-      - name: install NDK
-        if: steps.cache-ndk.outputs.cache-hit != 'true'
-        run: |
-          set -x
-          echo "y" | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT} 2>&1
-          if [ $? -ne 0 ]; then
-              echo "SDK Manager command failed"
-              exit 1
-          fi
-          set +x
+#      - name: install NDK
+#        if: steps.cache-ndk.outputs.cache-hit != 'true'
+#        run: |
+#          set -x
+#          echo "y" | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT} 2>&1
+#          if [ $? -ne 0 ]; then
+#              echo "SDK Manager command failed"
+#              exit 1
+#          fi
+#          set +x
+#          ls -al ${ANDROID_SDK_ROOT}/ndk
+
+      - run: |
+          ls -al ${ANDROID_SDK_ROOT}/ndk
+          rm -rf ${{ env.ANDROID_SDK_ROOT }}/ndk/*
           ls -al ${ANDROID_SDK_ROOT}/ndk
 
       - name: setup gradle
