Update android-build.yml

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -20,49 +20,28 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
-      - name: ensure lite files also updated
+      - name: ensure *.lite are also chandeg
         if: matrix.build == 'lite'
         run: |
           git fetch origin master > /dev/null 2>&1
-          git branch
           files=(
             "app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt"
             "app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt.lite"
             "app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt"
             "app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt.lite"
             "app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt"
-            "app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite")
-
-          any_changes=false
-
-          check_file_pair() {
-            local file1=$1
-            local file2=$2
-
-            # Check if either file has been modified in the commit range
-            if git diff --name-only HEAD origin/master | grep -E "^($file1|$file2)$" > /dev/null; then
-              any_changes=true
-              if ! git diff --name-only HEAD origin/master | grep -E "^($file1)$" > /dev/null ||
-                 ! git diff --name-only HEAD origin/master | grep -E "^($file2)$" > /dev/null; then
-                errors+=("Error: Both $file1 and $file2 must be changed together.")
-              fi
-            fi
-          }
-
+            "app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt.lite"
+          )
+          errors=()
           for ((i=0; i<${#files[@]}; i+=2)); do
-            check_file_pair "${files[i]}" "${files[i+1]}"
+            file1=${files[i]}
+            file2=${files[i+1]}
+            changes=$(git diff --name-only HEAD origin/master | grep -E "^($file1|$file2)$")
+            if [ -n "$changes" ] && (! echo "$changes" | grep -qE "^($file1)$" || ! echo "$changes" | grep -qE "^($file2)$"); then
+              errors+=("Error: Both $file1 and $file2 must be changed together.")
+            fi
           done
-
-          if [ ${#errors[@]} -gt 0 ]; then
-            for error in "${errors[@]}"; do
-              echo "$error"
-            done
-            exit 1
-          fi
-
-          if [ "$any_changes" = true ]; then
-            echo "All file pairs have changes."
-          fi
+          [ ${#errors[@]} -gt 0 ] && { printf "%s\n" "${errors[@]}"; exit 1; }
 
       - name: diff the code to get lite
         run: |
