Update android-build.yml

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -22,39 +22,29 @@ jobs:
       - name: checkout repository code
         uses: actions/checkout@v4
 
-      - name: ensure *.lite also change
+      - name: check for .lite changes
         if: matrix.build == 'lite'
         run: |
+          echo "checking for .lite changes..."
           git fetch origin master > /dev/null 2>&1
-          echo 0
-          declare -a main_files=(
+          files=(
             "app/src/main/AndroidManifest.xml"
             "app/src/main/java/org/ole/planet/myplanet/base/BaseContainerFragment.kt"
             "app/src/main/java/org/ole/planet/myplanet/base/PermissionActivity.kt"
             "app/src/main/java/org/ole/planet/myplanet/ui/dashboard/DashboardActivity.kt"
           )
-          echo 1
-          declare -a errors=()
-          echo 2
-          for file1 in "${defaults[@]}"; do
-            file2="${file1}.lite"  # Corresponding .lite file
-            changes=$(git diff --name-only HEAD origin/master | grep -E "^($file1|$file2)$")
-            if [ -n "$changes" ]; then
-              if ! echo "$changes" | grep -q "^$file1$"; then
-                errors+=("Error: $file1 has changed, but $file2 has not.")
-              elif ! echo "$changes" | grep -q "^$file2$"; then
-                errors+=("Error: $file2 has changed, but $file1 has not.")
+          checkchanges() {
+            if git diff --name-only origin/main HEAD | grep -q "$1"; then
+              if ! git diff --name-only origin/main HEAD | grep -q "$2"; then
+                echo "error: changes made to $1 but not to $2"
+                exit 1
               fi
             fi
+          }
+          for file in "${files[@]}"; do
+            checkchanges "$file" "$file.lite"
+            checkchanges "$file.lite" "$file"
           done
-          echo 3
-          if [ ${#errors[@]} -gt 0 ]; then
-            for error in "${errors[@]}"; do
-              echo "$error"
-            done
-            echo 4
-            exit 1
-          fi
 
       - name: diff the code to get lite
         if: matrix.build == 'lite'
