Update android-release.yml

diff --git a/.github/workflows/android-release.yml b/.github/workflows/android-release.yml
--- a/.github/workflows/android-release.yml
+++ b/.github/workflows/android-release.yml
@@ -56,7 +56,18 @@ jobs:
 
       - name: install NDK
         run: |
-          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${ANDROID_NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT}
+          set -x
+          echo "ANDROID_HOME is set to: ${ANDROID_HOME}"
+          echo "ANDROID_SDK_ROOT is set to: ${ANDROID_SDK_ROOT}"
+          echo "ANDROID_NDK_VERSION is set to: ${ANDROID_NDK_VERSION}"
+          #SDK_MANAGER_COMMAND="${ANDROID_HOME}/tools/bin/sdkmanager --install \"ndk;${ANDROID_NDK_VERSION}\" --sdk_root=${ANDROID_SDK_ROOT}"
+          SDK_MANAGER_COMMAND="${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install \"ndk;${ANDROID_NDK_VERSION}\" --sdk_root=${ANDROID_SDK_ROOT}"
+          echo "y" | sudo ${SDK_MANAGER_COMMAND} 2>&1
+          if [ $? -ne 0 ]; then
+              echo "SDK Manager command failed"
+              exit 1
+          fi
+          set +x
           chmod +x ./gradlew
 
       - name: build release APK and AAB
