Update android-release.yml

diff --git a/.github/workflows/android-release.yml b/.github/workflows/android-release.yml
--- a/.github/workflows/android-release.yml
+++ b/.github/workflows/android-release.yml
@@ -105,6 +105,26 @@ jobs:
           releaseName: "${{ env.ANDROID_VERSION_CODE }} (${{ env.ANDROID_VERSION_NAME }})"
           status: completed
 
+      - name: upload APK to Firebase Test Lab
+        if: github.ref != 'refs/heads/master' && (matrix.build == 'lite')
+        env:
+          FIREBASE_TOKEN: ${{ secrets.ROBOT_KEY }}
+        run: |
+          ls -al output/
+          npm install -g firebase-tools
+          if [ -f output/myPlanet.apk ]; then
+            firebase test android run \
+              --type robo \
+              --app output/myPlanet.apk \
+              --project myplanet-2eee1 \
+              --results-bucket myPlanet \
+              --results-dir test-results/myPlanet/$(date +%Y%m%d_%H%M%S) \
+              --timeout 900s
+          else
+            echo "APK file not found!"
+            exit 1
+          fi
+
       - name: rename APK and AAB with version and branch for artifact
         if: github.ref != 'refs/heads/master'
         run: |
@@ -132,24 +152,6 @@ jobs:
           overwrite: 'true'
           file_glob: 'true'
 
-      - name: upload APK to Firebase Test Lab
-        if: github.ref != 'refs/heads/master' && (matrix.build == 'lite')
-        env:
-          FIREBASE_TOKEN: ${{ secrets.ROBOT_KEY }}
-        run: |
-          npm install -g firebase-tools
-          if [ -f output/myPlanet.apk ]; then
-            firebase test android run \
-              --type robo \
-              --app output/myPlanet-${{ env.ANDROID_VERSION_NAME }}-${{ env.BRANCHNAME }}.apk \
-              --project myplanet-2eee1 \
-              --results-bucket myPlanet \
-              --results-dir test-results/myPlanet/$(date +%Y%m%d_%H%M%S) \
-              --timeout 900s
-          else
-            echo "APK file not found!"
-            exit 1
-          fi
 
       - name: send success message to discord
         if: (github.ref == 'refs/heads/master') && (matrix.build != 'lite')
