Update android-release.yml

diff --git a/.github/workflows/android-release.yml b/.github/workflows/android-release.yml
--- a/.github/workflows/android-release.yml
+++ b/.github/workflows/android-release.yml
@@ -98,29 +98,6 @@ jobs:
           releaseName: "${{ env.ANDROID_VERSION_CODE }} (${{ env.ANDROID_VERSION_NAME }})"
           status: completed
 
-      - name: upload APK to Firebase Test Lab
-        if: github.ref != 'refs/heads/master' && (matrix.build == 'lite')
-        env:
-          FIREBASE_TOKEN: ${{ secrets.ROBOT_KEY }}
-        run: |
-          ls -al output/
-          npm install -g firebase-tools
-          firebase --version
-          firebase test android run --help
-          firebase projects:list
-          if [ -f output/myPlanet.apk ]; then
-            firebase test android run \
-              --app output/myPlanet.apk \
-              --project myplanet-2eee1 \
-              --type robo \
-              --results-bucket myPlanet \
-              --results-dir test-results/myPlanet/$(date +%Y%m%d_%H%M%S) \
-              --timeout 900s
-          else
-            echo "APK file not found!"
-            exit 1
-          fi
-
       - name: publish AAB to playstore fallback
         if: github.event_name != 'workflow_dispatch' && matrix.build == 'lite' && steps.playstore.outcome == 'failure'
         uses: dogi/upload-google-play@v1.1.4
@@ -132,6 +109,31 @@ jobs:
           releaseName: "${{ env.ANDROID_VERSION_CODE }} (${{ env.ANDROID_VERSION_NAME }})"
           status: completed
           changesNotSentForReview: true
+
+      - name: upload APK to Firebase Test Lab
+        if: github.ref != 'refs/heads/master' && (matrix.build == 'lite')
+        env:
+          FIREBASE_TOKEN: ${{ secrets.ROBOT_KEY }}
+        run: |
+          ls -al output/
+          npm install -g firebase-tools
+          firebase --version
+          #firebase projects:list
+          if [ -f output/myPlanet.apk ]; then
+            gcloud config set project ***
+            #gcloud firebase test android models list
+            gcloud firebase test android run \
+              --type robo \
+              --app output/myPlanet.apk \
+              --results-bucket ***-results \
+              --results-dir test-results/myPlanet/$(date +%Y%m%d_%H%M%S) \
+              --timeout 900s \
+              --device model=MediumPhone.arm,version=34,locale=es,orientation=portrait
+              #--device model=shiba,version=34,locale=es,orientation=portrait
+          else
+            echo "APK file not found!"
+            exit 1
+          fi
 
       - name: rename APK and AAB with version and branch for artifact
         if: github.event_name == 'workflow_dispatch'
